spring:
  application:
    name: sopt-temu
  profiles:
    group:
      local: local-db, local-port, common
      prod: prod-db, prod-port, common
    active: local

---
# ?? ??
spring:
  config:
    activate:
      on-profile: common
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true

---
# ??? DB
spring:
  config:
    activate:
      on-profile: local-db
  datasource:
    url: ${LOCAL_DATASOURCE_URL}
    username: ${LOCAL_DATASOURCE_USERNAME}
    password: ${LOCAL_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

---
# ?? ??
spring:
  config:
    activate:
      on-profile: local-port
server:
  port: 8081

---
# ??? DB
spring:
  config:
    activate:
      on-profile: prod-db
  datasource:
    url: ${PROD_DATASOURCE_URL}
    username: ${PROD_DATASOURCE_USERNAME}
    password: ${PROD_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

---
# ?? ??
spring:
  config:
    activate:
      on-profile: prod-port
server:
  port: 8080